apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: kong-db-init
  name: kong-db-init
  namespace: live-kong
spec:
  template:
    metadata:
      labels:
        app: kong-db-init
    spec:
      restartPolicy: Never
      containers:
      - name: kong-db-init
        imagePullPolicy: "IfNotPresent"
        image: "192.168.0.121:5000/basic/kong"
        args: [ "/bin/sh", "-c", "kong migrations bootstrap" ]
        env:
        - name: KONG_DATABASE
          value: "postgres"
        - name: KONG_PG_DATABASE
          value: "live-kong"
        - name: KONG_PG_HOST
          value: "192.168.0.121"
        - name: KONG_PG_PASSWORD
          value: "ek5xN1dMeHZvY0k3"
        - name: KONG_PG_USER
          value: "live-kong"
        - name: KONG_PG_PORT
          value: "5432"
      imagePullSecrets:
        - name: harborsecretname