apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: live-postgresql
  namespace: live-kong
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
        storage: 5Gi