apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: live-kong
spec:
  type: ClusterIP
  ports:
  - name: redis-port
    port: 6379
    targetPort: redis-port
  selector:
    app: redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
  namespace: live-kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: 192.168.10.215:5000/basic/redis:5.0-alpine
        imagePullPolicy: Always
        env:
        - name: REDIS_PASSWORD
          value: "L9Ut7625E0dDdgf"
        ports:
        - name: redis-port
          containerPort: 6379
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
        lifecycle:
          postStart:
            exec:
              command: [ "/bin/sh", "-c", "redis-cli config set requirepass L9Ut7625E0dDdgf" ]
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
          - mountPath: /bitnami/redis
            name: data
      imagePullSecrets:
        - name: harborsecretname
      volumes:
      - name: data
        hostPath:
          path: /data/container/sentry/redis